# Form implementation generated from reading ui file 'Forms/LessonFormDesign.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_LessonWindow(object):
    def setupUi(self, LessonWindow):
        LessonWindow.setObjectName("LessonWindow")
        LessonWindow.resize(769, 435)
        self.centralwidget = QtWidgets.QWidget(parent=LessonWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.prevTaskButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.prevTaskButton.setGeometry(QtCore.QRect(20, 370, 181, 28))
        self.prevTaskButton.setObjectName("prevTaskButton")
        self.nextTaskButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.nextTaskButton.setGeometry(QtCore.QRect(570, 370, 181, 28))
        self.nextTaskButton.setObjectName("nextTaskButton")
        self.taskWidget = QtWidgets.QWidget(parent=self.centralwidget)
        self.taskWidget.setGeometry(QtCore.QRect(40, 20, 701, 331))
        self.taskWidget.setAutoFillBackground(False)
        self.taskWidget.setStyleSheet("background-color: rgb(211, 211, 211);")
        self.taskWidget.setObjectName("taskWidget")
        self.label = QtWidgets.QLabel(parent=self.taskWidget)
        self.label.setGeometry(QtCore.QRect(100, 10, 521, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.layoutWidget = QtWidgets.QWidget(parent=self.taskWidget)
        self.layoutWidget.setGeometry(QtCore.QRect(40, 40, 631, 31))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.ironsWordsLayout = QtWidgets.QVBoxLayout()
        self.ironsWordsLayout.setObjectName("ironsWordsLayout")
        self.label_2 = QtWidgets.QLabel(parent=self.layoutWidget)
        self.label_2.setObjectName("label_2")
        self.ironsWordsLayout.addWidget(self.label_2)
        self.horizontalLayout.addLayout(self.ironsWordsLayout)
        spacerItem = QtWidgets.QSpacerItem(100, 20, QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.russianWordsLayout = QtWidgets.QVBoxLayout()
        self.russianWordsLayout.setObjectName("russianWordsLayout")
        self.comboBox = QtWidgets.QComboBox(parent=self.layoutWidget)
        self.comboBox.setObjectName("comboBox")
        self.russianWordsLayout.addWidget(self.comboBox)
        self.horizontalLayout.addLayout(self.russianWordsLayout)
        self.verticalLayoutWidget = QtWidgets.QWidget(parent=self.taskWidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(40, 40, 631, 281))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.allWordsVerticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.allWordsVerticalLayout.setContentsMargins(0, 0, 0, 0)
        self.allWordsVerticalLayout.setObjectName("allWordsVerticalLayout")
        LessonWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(parent=LessonWindow)
        self.statusbar.setObjectName("statusbar")
        LessonWindow.setStatusBar(self.statusbar)

        self.retranslateUi(LessonWindow)
        QtCore.QMetaObject.connectSlotsByName(LessonWindow)

    def retranslateUi(self, LessonWindow):
        _translate = QtCore.QCoreApplication.translate
        LessonWindow.setWindowTitle(_translate("LessonWindow", "MainWindow"))
        self.prevTaskButton.setText(_translate("LessonWindow", "Предыдущее задание"))
        self.nextTaskButton.setText(_translate("LessonWindow", "Следующее задание"))
        self.label.setText(_translate("LessonWindow", "Сопоставьте осетинские слова и их перевод на русский"))
        self.label_2.setText(_translate("LessonWindow", "TextLabel"))
