# Form implementation generated from reading ui file 'Forms/LessonTaskImagesFormDesign.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_LessonWindowImages(object):
    def setupUi(self, LessonWindow):
        LessonWindow.setObjectName("LessonWindow")
        LessonWindow.resize(769, 435)
        self.centralwidget = QtWidgets.QWidget(parent=LessonWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.taskWidget = QtWidgets.QWidget(parent=self.centralwidget)
        self.taskWidget.setGeometry(QtCore.QRect(40, 20, 701, 331))
        self.taskWidget.setAutoFillBackground(False)
        self.taskWidget.setStyleSheet("background-color: rgb(211, 211, 211);")
        self.taskWidget.setObjectName("taskWidget")
        self.label = QtWidgets.QLabel(parent=self.taskWidget)
        self.label.setGeometry(QtCore.QRect(110, 10, 471, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.getResButton = QtWidgets.QPushButton(parent=self.taskWidget)
        self.getResButton.setGeometry(QtCore.QRect(250, 290, 211, 31))
        self.getResButton.setObjectName("getResButton")
        self.horizontalLayoutWidget = QtWidgets.QWidget(parent=self.taskWidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(20, 60, 661, 221))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.layoutWidget = QtWidgets.QWidget(parent=self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(30, 370, 721, 30))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.prevTaskButton = QtWidgets.QPushButton(parent=self.layoutWidget)
        self.prevTaskButton.setObjectName("prevTaskButton")
        self.horizontalLayout_2.addWidget(self.prevTaskButton)
        self.stopLessonButton = QtWidgets.QPushButton(parent=self.layoutWidget)
        self.stopLessonButton.setObjectName("stopLessonButton")
        self.horizontalLayout_2.addWidget(self.stopLessonButton)
        self.nextTaskButton = QtWidgets.QPushButton(parent=self.layoutWidget)
        self.nextTaskButton.setObjectName("nextTaskButton")
        self.horizontalLayout_2.addWidget(self.nextTaskButton)
        LessonWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(parent=LessonWindow)
        self.statusbar.setObjectName("statusbar")
        LessonWindow.setStatusBar(self.statusbar)

        self.retranslateUi(LessonWindow)
        QtCore.QMetaObject.connectSlotsByName(LessonWindow)

    def retranslateUi(self, LessonWindow):
        _translate = QtCore.QCoreApplication.translate
        LessonWindow.setWindowTitle(_translate("LessonWindow", "MainWindow"))
        self.label.setText(_translate("LessonWindow", "Сопоставьте изображения с осетинскими словами"))
        self.getResButton.setText(_translate("LessonWindow", "Проверить"))
        self.prevTaskButton.setText(_translate("LessonWindow", "Предыдущее задание"))
        self.stopLessonButton.setText(_translate("LessonWindow", "Завершить занятие"))
        self.nextTaskButton.setText(_translate("LessonWindow", "Следующее задание"))
